In [1]:
#svm

from sklearn.svm import SVC
from sklearn import svm
import numpy as np

In [2]:
X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

In [3]:

l=SVC(C=1e5,kernel='linear')
l.fit(X,y)

print('w= ',l.coef_)
print('b= ',l.intercept_)
print('Indices of support vectors= ',l.support_)
print('Support vectors= ',l.support_vectors_)
print('No. of support vectors from each class= ',l.n_support_)
print('coefficient of support vectors in decision function= ',np.abs(l.dual_coef_))

w=  [[ 0.25 -0.25]]
b=  [-0.75]
Indices of support vectors=  [2 3]
Support vectors=  [[ 2.  3.]
 [ 6. -1.]]
No. of support vectors from each class=  [1 1]
coefficient of support vectors in decision function=  [[0.0625 0.0625]]


In [5]:
import pandas as pd
data=pd.read_csv('/home/ignis/Desktop/dataaset/glass.csv')
data.head()

x=data.drop('Type',axis=1)
y=data.Type

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [7]:
linear=svm.SVC(kernel='linear')
linear.fit(x_train,y_train)


SVC(kernel='linear')

In [8]:
print(linear.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [7.40000e+01 1.51631e+00 1.33400e+01 3.57000e+00 1.57000e+00 7.28700e+01
  6.10000e-01 7.89000e+00 0.00000e+00 0.00000e+00]
 [7.10000e+01 1.51574e+00 1.48600e+01 3.67000e+00 1.74000e+00 7.18700e+01
  1.60000e-01 7.36000e+00 0.00000e+00 1.20000e-01]
 [1.44000e+02 1.51709e+00 1.30000e+01 3.47000e+00 1.79000e+00 7.27200e+01
  6.60000e-01 8.18000e+00 0.00000e+00 0.00000e+00]
 [1.47000e+02 1.51769e+00 1.36500e+01 3.66000e+00 1.11000e+00 7.27700e+01
  1.10000e-01 8.60000e+00 0.00000e+00 0.00000e+00]
 [1.62000e+02 1.51934e+00 1.36400e+01 3.54000e+00 7.50000e-01 7.26500e+01
  1.60000e-01 8.89000e+00 1.50000e-01 2.40000e-01]
 [1.75000e+02 1.52058e+00 1.28500e+01 1.61000e+00 2.17000e+00 7.21800e+01
  7.60000e-01 9.70000e+00 2.40000e-01 5.10000e-01]
 [1.67000e+02 1.52151e+00 1.10300e+01 1.71000e+00 1.56000e+00 7.34400e+01
  5.80000e-01 1.16200e+01 0.00000e+00 0.00000e+00]


In [9]:
print(linear.n_support_)


[1 3 2 4 3 4]


In [10]:

y_pred=linear.predict(x_test)

In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))



0.9846153846153847


In [12]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[19  0  0  0  0  0]
 [ 0 28  1  0  0  0]
 [ 0  0  3  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0 10]]


In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        19
           2       1.00      0.97      0.98        29
           3       0.75      1.00      0.86         3
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00        10

    accuracy                           0.98        65
   macro avg       0.96      0.99      0.97        65
weighted avg       0.99      0.98      0.99        65



In [14]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

In [15]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)z

SyntaxError: invalid syntax (<ipython-input-15-544ff713466b>, line 3)